/* Circuitos arcade inspirados nos traçados reais, sem reprodução de assets/logos.
   Biomas: 0 costa, 1 cidade, 4 floresta, 7 túnel (índices originais do mundo).
   enter/hold/leave em segmentos; hill é a variação de altura em SEGLEN.
   A soma das colinas é zero e a última seção sempre termina em uma reta. */
(function (ND) {
    "use strict";

    ND.circuits = [
        {
            id: "interlagos",
            name: "Interlagos",
            shortName: "INTERLAGOS",
            country: "BR",
            description:
                "Versão arcade: S do Senna, Curva do Sol e Junção entre a cidade e a mata.",
            phase: 0.04,
            sections: [
                {
                    name: "Reta dos Boxes",
                    enter: 24,
                    hold: 72,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 1,
                },
                {
                    name: "S do Senna — entrada",
                    enter: 18,
                    hold: 28,
                    leave: 18,
                    curve: -4.2,
                    hill: -6,
                    biome: 1,
                },
                {
                    name: "S do Senna — saída",
                    enter: 16,
                    hold: 24,
                    leave: 16,
                    curve: 3.8,
                    hill: -4,
                    biome: 1,
                },
                {
                    name: "Curva do Sol",
                    enter: 24,
                    hold: 42,
                    leave: 24,
                    curve: -2.8,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Reta Oposta",
                    enter: 24,
                    hold: 74,
                    leave: 24,
                    curve: 0,
                    hill: 2,
                    biome: 4,
                },
                {
                    name: "Descida do Lago",
                    enter: 20,
                    hold: 38,
                    leave: 20,
                    curve: -3.5,
                    hill: -4,
                    biome: 4,
                },
                {
                    name: "Ferradura",
                    enter: 22,
                    hold: 36,
                    leave: 22,
                    curve: 3.4,
                    hill: 6,
                    biome: 4,
                },
                {
                    name: "Laranjinha",
                    enter: 18,
                    hold: 30,
                    leave: 18,
                    curve: 3.8,
                    hill: 4,
                    biome: 4,
                },
                {
                    name: "Pinheirinho",
                    enter: 18,
                    hold: 26,
                    leave: 18,
                    curve: -3.6,
                    hill: -2,
                    biome: 4,
                },
                {
                    name: "Bico de Pato",
                    enter: 18,
                    hold: 26,
                    leave: 18,
                    curve: 4.5,
                    hill: -2,
                    biome: 4,
                },
                {
                    name: "Junção",
                    enter: 24,
                    hold: 36,
                    leave: 24,
                    curve: -4,
                    hill: 6,
                    biome: 4,
                },
                {
                    name: "Subida dos Boxes",
                    enter: 24,
                    hold: 54,
                    leave: 24,
                    curve: -1.5,
                    hill: 10,
                    biome: 1,
                },
                {
                    name: "Reta de chegada",
                    enter: 24,
                    hold: 60,
                    leave: 24,
                    curve: 0,
                    hill: -10,
                    biome: 1,
                },
            ],
        },
        {
            id: "monaco",
            name: "Mônaco",
            shortName: "MÔNACO",
            country: "MC",
            description:
                "Versão arcade urbana: Cassino, Loews, Túnel e Rascasse junto à costa.",
            phase: 0.08,
            sections: [
                {
                    name: "Reta dos Boxes",
                    enter: 24,
                    hold: 54,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 1,
                },
                {
                    name: "Sainte Dévote",
                    enter: 22,
                    hold: 34,
                    leave: 22,
                    curve: 4,
                    hill: 2,
                    biome: 1,
                },
                {
                    name: "Beau Rivage",
                    enter: 24,
                    hold: 50,
                    leave: 24,
                    curve: -1,
                    hill: 10,
                    biome: 1,
                },
                {
                    name: "Cassino",
                    enter: 20,
                    hold: 36,
                    leave: 20,
                    curve: 3.4,
                    hill: -4,
                    biome: 1,
                },
                {
                    name: "Mirabeau",
                    enter: 18,
                    hold: 30,
                    leave: 18,
                    curve: 4.2,
                    hill: -5,
                    biome: 1,
                },
                {
                    name: "Loews",
                    enter: 20,
                    hold: 32,
                    leave: 20,
                    curve: -4.8,
                    hill: -3,
                    biome: 1,
                },
                {
                    name: "Portier",
                    enter: 18,
                    hold: 30,
                    leave: 18,
                    curve: 3.8,
                    hill: 0,
                    biome: 0,
                },
                {
                    name: "Túnel",
                    enter: 24,
                    hold: 72,
                    leave: 24,
                    curve: 1.5,
                    hill: 0,
                    biome: 7,
                },
                {
                    name: "Chicane — entrada",
                    enter: 16,
                    hold: 24,
                    leave: 16,
                    curve: -4.6,
                    hill: 0,
                    biome: 0,
                },
                {
                    name: "Chicane — saída",
                    enter: 16,
                    hold: 24,
                    leave: 16,
                    curve: 4.4,
                    hill: 0,
                    biome: 0,
                },
                {
                    name: "Tabac",
                    enter: 20,
                    hold: 36,
                    leave: 20,
                    curve: -3.7,
                    hill: 0,
                    biome: 0,
                },
                {
                    name: "Piscina",
                    enter: 16,
                    hold: 28,
                    leave: 16,
                    curve: 3.2,
                    hill: 0,
                    biome: 0,
                },
                {
                    name: "Rascasse",
                    enter: 22,
                    hold: 30,
                    leave: 22,
                    curve: 4.6,
                    hill: 0,
                    biome: 1,
                },
                {
                    name: "Reta de chegada",
                    enter: 24,
                    hold: 48,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 1,
                },
            ],
        },
        {
            id: "monza",
            name: "Monza",
            shortName: "MONZA",
            country: "IT",
            description:
                "Versão arcade veloz no bosque: Rettifilo, Roggia, Lesmo, Ascari e Parabolica.",
            phase: 0.02,
            sections: [
                {
                    name: "Reta dos Boxes",
                    enter: 30,
                    hold: 90,
                    leave: 30,
                    curve: 0,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Rettifilo — direita",
                    enter: 18,
                    hold: 24,
                    leave: 18,
                    curve: 4.2,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Rettifilo — esquerda",
                    enter: 18,
                    hold: 24,
                    leave: 18,
                    curve: -4.2,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Curva Grande",
                    enter: 24,
                    hold: 64,
                    leave: 24,
                    curve: 1.8,
                    hill: 2,
                    biome: 4,
                },
                {
                    name: "Roggia — entrada",
                    enter: 18,
                    hold: 24,
                    leave: 18,
                    curve: -4.1,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Roggia — saída",
                    enter: 18,
                    hold: 24,
                    leave: 18,
                    curve: 4.1,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Lesmo 1",
                    enter: 20,
                    hold: 32,
                    leave: 20,
                    curve: 3.6,
                    hill: 2,
                    biome: 4,
                },
                {
                    name: "Lesmo 2",
                    enter: 20,
                    hold: 32,
                    leave: 20,
                    curve: 3.9,
                    hill: -2,
                    biome: 4,
                },
                {
                    name: "Serraglio",
                    enter: 24,
                    hold: 78,
                    leave: 24,
                    curve: 0,
                    hill: -2,
                    biome: 4,
                },
                {
                    name: "Ascari — entrada",
                    enter: 18,
                    hold: 24,
                    leave: 18,
                    curve: -3.8,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Ascari — miolo",
                    enter: 18,
                    hold: 26,
                    leave: 18,
                    curve: 3.5,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Ascari — saída",
                    enter: 18,
                    hold: 24,
                    leave: 18,
                    curve: -3.3,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Reta de trás",
                    enter: 24,
                    hold: 60,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Parabolica",
                    enter: 26,
                    hold: 58,
                    leave: 26,
                    curve: 2.9,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Reta de chegada",
                    enter: 24,
                    hold: 60,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 4,
                },
            ],
        },
        {
            id: "suzuka",
            name: "Suzuka",
            shortName: "SUZUKA",
            country: "JP",
            description:
                "Versão arcade entre colinas e floresta: Esses, Degner, Hairpin, Spoon e 130R.",
            phase: 0.94,
            sections: [
                {
                    name: "Reta principal",
                    enter: 24,
                    hold: 58,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Primeira Curva",
                    enter: 22,
                    hold: 38,
                    leave: 22,
                    curve: 3.4,
                    hill: 2,
                    biome: 4,
                },
                {
                    name: "Esses — esquerda",
                    enter: 16,
                    hold: 24,
                    leave: 16,
                    curve: -3.4,
                    hill: 3,
                    biome: 4,
                },
                {
                    name: "Esses — direita",
                    enter: 16,
                    hold: 24,
                    leave: 16,
                    curve: 3.5,
                    hill: 3,
                    biome: 4,
                },
                {
                    name: "Esses — subida",
                    enter: 18,
                    hold: 30,
                    leave: 18,
                    curve: -3.2,
                    hill: 4,
                    biome: 4,
                },
                {
                    name: "Dunlop",
                    enter: 24,
                    hold: 42,
                    leave: 24,
                    curve: -2.4,
                    hill: -2,
                    biome: 4,
                },
                {
                    name: "Degner 1",
                    enter: 18,
                    hold: 26,
                    leave: 18,
                    curve: 3.4,
                    hill: -4,
                    biome: 4,
                },
                {
                    name: "Degner 2",
                    enter: 18,
                    hold: 26,
                    leave: 18,
                    curve: 4.3,
                    hill: -4,
                    biome: 4,
                },
                {
                    name: "Hairpin",
                    enter: 22,
                    hold: 32,
                    leave: 22,
                    curve: -4.6,
                    hill: -2,
                    biome: 4,
                },
                {
                    name: "200R",
                    enter: 24,
                    hold: 46,
                    leave: 24,
                    curve: 1.5,
                    hill: 2,
                    biome: 4,
                },
                {
                    name: "Spoon",
                    enter: 24,
                    hold: 50,
                    leave: 24,
                    curve: -3.6,
                    hill: -4,
                    biome: 4,
                },
                {
                    name: "Reta Oposta",
                    enter: 24,
                    hold: 70,
                    leave: 24,
                    curve: 0,
                    hill: 2,
                    biome: 4,
                },
                {
                    name: "130R",
                    enter: 24,
                    hold: 42,
                    leave: 24,
                    curve: -2.2,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Chicane — entrada",
                    enter: 16,
                    hold: 22,
                    leave: 16,
                    curve: 4.4,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Chicane — saída",
                    enter: 16,
                    hold: 22,
                    leave: 16,
                    curve: -4.4,
                    hill: 0,
                    biome: 4,
                },
                {
                    name: "Reta de chegada",
                    enter: 24,
                    hold: 52,
                    leave: 24,
                    curve: 0,
                    hill: 0,
                    biome: 4,
                },
            ],
        },
    ];
})((window.NeonDrive = window.NeonDrive || {}));
